select * from tbl_Employees;
select * from tbl_Departments;
select * from tbl_Orders;
select * from tbl_OrderDetails;
select * from tbl_Products;


--Q11. customer who placed largest total value of orders
create view vw_ordersAndOrderDetails
as
select tbl_Orders.orderID, tbl_Orders.customerID, tbl_OrderDetails.productID, tbl_OrderDetails.quantity
from tbl_Orders
full join tbl_OrderDetails
on tbl_Orders.orderID = tbl_OrderDetails.orderID;

select * from vw_ordersAndOrderDetails;

create view vw_OrderOrderdetailsAndProducts2
as
select vw_ordersAndOrderDetails.orderID, vw_ordersAndOrderDetails.customerID, vw_ordersAndOrderDetails.productID, vw_ordersAndOrderDetails.quantity, tbl_Products.productName, tbl_Products.unitPrice, (vw_ordersAndOrderDetails.quantity*tbl_Products.unitPrice) as totalPrice
from vw_ordersAndOrderDetails
full join tbl_Products
on vw_ordersAndOrderDetails.productID = tbl_Products.productID;

select * from vw_OrderOrderdetailsAndProducts2;

select customerID from vw_OrderOrderdetailsAndProducts2
where totalPrice = (select MAX(totalPrice) from vw_OrderOrderdetailsAndProducts2);



--Q12. customer ordering highest quantity of products
select customerID from vw_OrderOrderdetailsAndProducts2
where quantity = (select MAX(quantity) from vw_OrderOrderdetailsAndProducts2);



--Q13. departments with more than five employees
create view vw_EmployeesAndDepartments
as
select tbl_Employees.employeeID, tbl_Employees.firstName, tbl_Employees.lastName, tbl_Employees.departmentID, tbl_Departments.departentName
from tbl_Employees
full join tbl_Departments
on tbl_Employees.departmentID = tbl_Departments.departmentID;

select * from vw_EmployeesAndDepartments;

select departentName
from vw_EmployeesAndDepartments
group by departentName
having count(employeeID) > 5;




--Q15. order with highest total price

select orderID from vw_OrderOrderdetailsAndProducts2
where totalPrice = (select max(totalPrice) from vw_OrderOrderdetailsAndProducts2);



--Q16. employees placing no order
create view vw_EmployeesAndOrders
as
select tbl_Employees.employeeID, tbl_Employees.firstName, tbl_Employees.lastName, tbl_Employees.departmentID, tbl_Orders.orderID, tbl_Orders.orderDate
from tbl_Employees
full outer join tbl_Orders
on tbl_Employees.employeeID = tbl_Orders.customerID;

select * from vw_EmployeesAndOrders;

select employeeID from vw_EmployeesAndOrders where orderID = NULL;



--Q17. Total revenue generated by each product
select productID, productName, totalPrice as revenueGenerated
from vw_OrderOrderdetailsAndProducts2;


--Q18. products ordered more than 100 times
select productID, productName 
from vw_OrderOrderdetailsAndProducts2
where quantity > 100;

--Q20. product with highest total revenue
select productID, productName, totalPrice as revenueGenerated
from vw_OrderOrderdetailsAndProducts2;

